### ISSUE TITLE
Eureka server cluster config

### ISSUE THREAD

**Issue by vuchl** [SteeltoeOSS/Dockerfiles#4]
Hello Steeltoe!

What do I need to do to setup 2 instances of the eureka-server docker image to work in a peer mode? Can I just add some configuration and restart the docker container? Or do I need to rebuild the container after editing `src/main/resources/application.properties`?

I have a instance of the container running on 2 separate VMs via 
`docker run publish 8761:8761 -d steeltoeoss/eureka-server`.
Where do I put the 
`eureka.client.serviceUrl.defaultZone=http://<first-ip>:8761/eureka,http://<second-ip>:8761/eureka`?

Regards Sebastian

**Comment by ccheetham** [comment]
Sebastion,

Any arguments to passed to `docker run...` are passed along to the Eureka server.  E.g.,
```
%  docker run --publish 8761:8761 steeltoeoss/eureka-server --eureka.client.serviceUrl.defaultZone=http://...
```

Here's a sample `docker-compose.yml` that sets `eureka.client.serviceUrl.defaultZone` for 2 peers:

```
version: '3'
services:
  eureka-peer-1:
    image: steeltoeoss/eureka-server
    ports:
      - 9001:8761
    entrypoint:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - eureka-server.jar
      - --eureka.client.serviceUrl.defaultZone=http://eureka-peer-1:8761/eureka,http://eureka-peer-2:8761/eureka
  eureka-peer-2:
    image: steeltoeoss/eureka-server
    ports:
      - 9002:8761
    entrypoint:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - eureka-server.jar
      - --eureka.client.serviceUrl.defaultZone=http://eureka-peer-1:8761/eureka,http://eureka-peer-2:8761/eureka
```
